### ISSUE TITLE
G4Navigator warnings

### ISSUE THREAD

**Issue by decibelcooper** [amentumspace/g4pbc#1]
Hello!  Thanks for your helpful work here!

I get warnings from G4Navigator that it's upset about not being notified about updates to the position.
```
-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : GeomNav1002
      issued by : G4Navigator::ComputeStep()
Accuracy error or slightly inaccurate position shift.
     The Step's starting point has moved 0.0794063 mm
     since the last call to a Locate method.
     This has resulted in moving 0.013607 mm  from the last point at which the safety      was calculated
     which is more than the computed safety= 0 mm  at that point.
     This difference is 0.013607 mm.
     The tolerated accuracy is 1e-06 mm.

*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------


-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : GeomNav1002
      issued by : G4Navigator::ComputeStep()
May lead to a crash or unreliable results.
        Position has shifted considerably without notifying the navigator !
        Tolerated safety: 1e-06
        Computed shift  : 0.000185149
*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------
```
I believe what it's referring to is needing an updated calculation for the safety.  These G4Exceptions come about from recognizing that the particle has been moved outside of the previous safety region.  It seems to me that this could be resolved by calling G4Navigator::ComputeSafety()?

**Comment by driwancornelius** [comment]
Hi, You're welcome, and thanks for the fix! I have merged the pull request. Cheers

**Comment by kumar8284** [comment]
> Hello! Thanks for your helpful work here!
> 
> I get warnings from G4Navigator that it's upset about not being notified about updates to the position.
> 
> ```
> -------- WWWW ------- G4Exception-START -------- WWWW -------
> *** G4Exception : GeomNav1002
>       issued by : G4Navigator::ComputeStep()
> Accuracy error or slightly inaccurate position shift.
>      The Step's starting point has moved 0.0794063 mm
>      since the last call to a Locate method.
>      This has resulted in moving 0.013607 mm  from the last point at which the safety      was calculated
>      which is more than the computed safety= 0 mm  at that point.
>      This difference is 0.013607 mm.
>      The tolerated accuracy is 1e-06 mm.
> 
> *** This is just a warning message. ***
> -------- WWWW -------- G4Exception-END --------- WWWW -------
> 
> 
> -------- WWWW ------- G4Exception-START -------- WWWW -------
> *** G4Exception : GeomNav1002
>       issued by : G4Navigator::ComputeStep()
> May lead to a crash or unreliable results.
>         Position has shifted considerably without notifying the navigator !
>         Tolerated safety: 1e-06
>         Computed shift  : 0.000185149
> *** This is just a warning message. ***
> -------- WWWW -------- G4Exception-END --------- WWWW -------
> ```
> 
> I believe what it's referring to is needing an updated calculation for the safety. These G4Exceptions come about from recognizing that the particle has been moved outside of the previous safety region. It seems to me that this could be resolved by calling G4Navigator::ComputeSafety()?
******************************************************************************
Hello do you have solution for this?
